version: "3.7"

services:
  api:
    container_name: nodejs-fruits-api
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017/fruits
      - PORT=3000
      - NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - .vscode:/api/.vscode
    ports: ["3000:3000"]
    tty: true

  mongo:
    container_name: mongo-db
    image: mongo
    volumes:
      - "./db:/data/db"
